server:
  port: 8087
  servlet:
    context-path: /@project.artifactId@
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory-service
    username: root
    password: root
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
  redis:
    host: localhost
    port: 6379
    timeout: 60000
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect
      generate_statistics: false
      show_sql: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  kafka:
    bootstrap-servers: localhost:29092